In [2]:
# 1D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [3]:
arr.append(6)
arr

[1, 2, 3, 4, 5, 6]

In [4]:
# Numpy Array Formation

import numpy as np
arr = np.array(arr)
print(arr.ndim)      # n Dimension
print(arr.shape)     # Dataset shape:Row and Columns
print(arr)

1
(6,)
[1 2 3 4 5 6]


In [5]:
# 2D Array

arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)

print(arr1.ndim)      # n Dimension
print(arr1.shape)     # Dataset shape:Row and Columns
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
# 3D Array

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)

print(arr2.ndim)      # n Dimension
print(arr2.shape)     # Dataset shape:Row and Columns
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

# summation of matrix
c = a + b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

# summation of matrix
c = a - b
print(c)

[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

# summation of matrix
c = a * b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

# summation of matrix
c = a / b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

print(c)
print(f'\n',d)
print(f'\n',e)

# summation of matrix
z = a + e 
print(f'\n',z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [0. 0. 0.]

 [1. 1. 1.]

 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [15]:
a * [2,3,4]

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [16]:
# Changing Dtype : DataType

a = np.array([1,2,3],dtype = 'float')
a

array([1., 2., 3.])

In [17]:
a = np.array([1,2,3],dtype = 'bool')
a

array([ True,  True,  True])

In [18]:
a = np.array([1,2,3],dtype = 'complex')
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
# Arange function

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Arange function

# np.arange(start,stop,step)

a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [21]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
num.reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
num.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [24]:
num.reshape(2,10)  # 2 Dimension

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [25]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [26]:
# Crate 3D Array
num.reshape(1,1,20)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]])

In [27]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [28]:
np.linspace(1,20,11)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

In [29]:
a = np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
# m:5  :--> No.of Rows and n:6 :--> No.of Coluns
arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
# Aggregate Function
arr.max(),arr.min(),arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)

In [33]:
arr.max()

29

In [34]:
arr.min()

0

In [35]:
arr.mean()

14.5

In [36]:
arr.std()

8.65544144839919

In [37]:
arr.var()

74.91666666666667

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr.sum(axis = 1) # Rows wise Addition

array([ 15,  51,  87, 123, 159])

In [ ]:
arr.sum(axis = 0)  # Coloumns wise Addition

array([60, 65, 70, 75, 80, 85])

In [41]:
arr[1:4]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
arr[1:4,2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [47]:
n = np.arange(50,100) # 1D Dimention
m = n.reshape(10,5)     # 2D Dimention
print(m.ndim)         # Checking Dimension : 2D
m[1:3,1:3]
m

2


array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [49]:
m[1:3,1:3]


array([[56, 57],
       [61, 62]])

In [51]:
m[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [56]:
a = np.arange(101,131, dtype="float")


In [57]:
print(a)

[101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114.
 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127. 128.
 129. 130.]


In [64]:
b = a.reshape(5,6)
print(b)
print(b.ndim)


[[101. 102. 103. 104. 105. 106.]
 [107. 108. 109. 110. 111. 112.]
 [113. 114. 115. 116. 117. 118.]
 [119. 120. 121. 122. 123. 124.]
 [125. 126. 127. 128. 129. 130.]]
2


In [65]:
b[3:,3:]

array([[122., 123., 124.],
       [128., 129., 130.]])

In [66]:
array = np.arange(101,131,dtype = 'float').reshape(1,5,6)
array[3:,3:]

array([], shape=(0, 2, 6), dtype=float64)

In [67]:
array

array([[[101., 102., 103., 104., 105., 106.],
        [107., 108., 109., 110., 111., 112.],
        [113., 114., 115., 116., 117., 118.],
        [119., 120., 121., 122., 123., 124.],
        [125., 126., 127., 128., 129., 130.]]])